/* libclrpc_call_vector.c
 * This file was auto-generated by gen_ocl_call_vector.pl
 */

/* __ocl_call_vector  */

#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

#include "CL/cl.h"

extern cl_int _clGetPlatformIDs(cl_uint,cl_platform_id*,cl_uint);
extern cl_int _clGetPlatformInfo(cl_platform_id,cl_platform_info,size_t,
        void*,size_t);
extern cl_int _clGetDeviceIDs(cl_platform_id,cl_device_type,cl_uint,
        cl_device_id*,cl_uint*);

typedef void (*cl_pfn_notify_t)(const char*, const void*, size_t, void*);
typedef void (*cl_pfn_notify2_t)(cl_program , void* );
typedef void (*cl_user_func_t)(void*);

static void* _cvec[] = { \
	_clGetPlatformIDs, \
	_clGetPlatformInfo, \
	_clGetDeviceIDs, 
#if 0
	clGetDeviceInfo, \
	clCreateContext, \
	clCreateContextFromType, \
	clRetainContext, \
	clReleaseContext, \
	clGetContextInfo, \
	clCreateCommandQueue, \
	clRetainCommandQueue, \
	clReleaseCommandQueue, \
	clGetCommandQueueInfo, \
	clSetCommandQueueProperty, \
	clCreateBuffer, \
	clCreateImage, \
	clRetainMemObject, \
	clReleaseMemObject, \
	clGetSupportedImageFormats, \
	clGetMemObjectInfo, \
	clGetImageInfo, \
	clCreateSampler, \
	clRetainSampler, \
	clReleaseSampler, \
	clGetSamplerInfo, \
	clCreateProgramWithSource, \
	clCreateProgramWithBinary, \
	clRetainProgram, \
	clReleaseProgram, \
	clBuildProgram, \
    clUnloadPlatformCompiler, \
	clGetProgramInfo, \
	clGetProgramBuildInfo, \
	clCreateKernel, \
	clCreateKernelsInProgram, \
	clRetainKernel, \
	clReleaseKernel, \
	clSetKernelArg, \
	clGetKernelInfo, \
	clGetKernelWorkGroupInfo, \
	clWaitForEvents, \
	clGetEventInfo, \
	clRetainEvent, \
	clReleaseEvent, \
	clGetEventProfilingInfo, \
	clFlush, \
	clFinish, \
	clEnqueueReadBuffer, \
	clEnqueueWriteBuffer, \
	clEnqueueCopyBuffer, \
	clEnqueueReadImage, \
	clEnqueueWriteImage, \
	clEnqueueCopyImage, \
	clEnqueueCopyImageToBuffer, \
	clEnqueueCopyBufferToImage, \
	clEnqueueMapBuffer, \
	clEnqueueMapImage, \
	clEnqueueUnmapMemObject, \
	clEnqueueNDRangeKernel, \
	clEnqueueTask, \
	clEnqueueNativeKernel, \
	clEnqueueMarkerWithWaitList, \
	clEnqueueBarrierWithWaitList, \
	clCreateFromGLBuffer, \
	clCreateFromGLTexture, \
	clCreateFromGLRenderbuffer, \
	clGetGLObjectInfo, \
	clGetGLTextureInfo, \
	clEnqueueAcquireGLObjects, \
	clEnqueueReleaseGLObjects,
#endif
	};

void** __ocl_call_vector = (void**)_cvec;
